name: CI

on:
  push:

jobs:
  test:
    name: Test Go
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Lint
        run: go vet ./...

      - name: Test
        run: make test
